In [2]:
import pandas as pd

df = pd.read_csv("data.csv", encoding="latin-1", header=None)
df.head()

,0,1,2,3,4,5
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [3]:
df.columns = ["sentiment", "id", "date", "query", "user", "text"]
df.head()

,sentiment,id,date,query,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [4]:
df = df[["text", "sentiment"]]
df.head()

                                                text  sentiment
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...          0
1  is upset that he can't update his Facebook by ...          0
2  @Kenichan I dived many times for the ball. Man...          0
3    my whole body feels itchy and like its on fire           0
4  @nationwideclass no, it's not behaving at all....          0

In [5]:
df["sentiment"] = df["sentiment"].replace(4, 1)
df["sentiment"].value_counts()

sentiment
0    800000
1    800000
Name: count, dtype: int64

In [6]:
df["depression"] = df["sentiment"].apply(lambda x: 1 if x == 0 else 0)

df.head()

                                                text  sentiment  depression
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...          0           1
1  is upset that he can't update his Facebook by ...          0           1
2  @Kenichan I dived many times for the ball. Man...          0           1
3    my whole body feels itchy and like its on fire           0           1
4  @nationwideclass no, it's not behaving at all....          0           1

In [7]:
df["depression"].value_counts()

depression
1    800000
0    800000
Name: count, dtype: int64

In [8]:
df = df[["text", "depression"]]
df.head()

                                                text  depression
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...           1
1  is upset that he can't update his Facebook by ...           1
2  @Kenichan I dived many times for the ball. Man...           1
3    my whole body feels itchy and like its on fire            1
4  @nationwideclass no, it's not behaving at all....           1